#!/bin/sh
#
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
if test $(uname | grep 'Darwin' 2>/dev/null)
then
	. script/homebrew
fi

# Run the install (I'd like to pull this out of rake, eventually)
rake install

